# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # This was the easiest way to get Python, the JRE and Maven in one image
      - image: openkbs/jre-mvn-py3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}-{{ checksum "pom.xml" }}

      - run:
          name: install dependencies
          # We need to install venv as the image doesn't provide it
          command: |
            pip install --upgrade pip setuptools
            python setup.py install
            mvn -q dependency:copy-dependencies -DoutputDirectory=./jars

      - save_cache:
          paths:
            - ./venv
            - ./jars
          key: v1-dependencies-{{ checksum "setup.py" }}-{{ checksum "pom.xml" }}

      - run:
          name: run tests
          command: ./test.sh

      - store_artifacts:
          path: test-reports
          destination: test-reports
